# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = "../Vagrantfile"
    docker.image = "rkuchimpos/docker-peercoind"
    docker.expose = ['9903','9904']
    docker.ports = ['19902:9904']
    docker.name = 'parstestnetA'
    docker.cmd = ['-debug', '-dns', '-rpcallowip=*', '-rpcpassword=bar', '-rpcuser=foo', '-testnet=1','-gen','-connect=127.0.0.1:9903', '-connect=127.0.0.1:9904']
    #docker.cmd = ['-rpcallowip=*','-testnet=1','-gen','-connect=127.0.0.1:9903', '-connect=127.0.0.1:9904']
  end
end
