# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = "../Vagrantfile"
    docker.image = "rkuchimpos/docker-peercoind"
    docker.expose = ['9903','9904']
    docker.ports = ['19903:9904']
    docker.name = 'parstestnetB'
    docker.link('parstestnetA:parstestnetA')
    docker.cmd = ['-debug','-dns', '-rpcallowip=*', '-rpcpassword=bar', '-rpcuser=foo', '-testnet=1','-gen','-connect=parstestnetA:9903','-connect=parstestnetA:9904']
    #docker.cmd = ['-rpcallowip=*','-testnet=1','-gen','-connect=parstestnet1:9903','-connect=parstestnet1:9904']
  end
end
